version: '3.8'

services:
  virtual-girlfriend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./server:/app/server
      - ./client:/app/client
    command: npm run dev
    restart: unless-stopped

  # Opcional: Redis para cache (futuro)
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data

# volumes:
#   redis_data: 