[build]
  command = "npm install && cd client && npm install && npm run typecheck && DISABLE_ESLINT_PLUGIN=true npm run build"
  publish = "client/build"

[build.environment]
  NODE_VERSION = "18"
  DISABLE_ESLINT_PLUGIN = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 