services:
  - type: web
    name: virtual-girlfriend-ai
    env: node
    buildCommand: npm run install-all && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /health
    autoDeploy: true 