apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtual-girlfriend-ai
  labels:
    app: virtual-girlfriend-ai
spec:
  replicas: 3
  selector:
    matchLabels:
      app: virtual-girlfriend-ai
  template:
    metadata:
      labels:
        app: virtual-girlfriend-ai
    spec:
      containers:
      - name: virtual-girlfriend-ai
        image: virtual-girlfriend-ai:latest
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "5000"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: virtual-girlfriend-secrets
              key: openai-api-key
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: virtual-girlfriend-secrets
              key: jwt-secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: virtual-girlfriend-service
spec:
  selector:
    app: virtual-girlfriend-ai
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: virtual-girlfriend-secrets
type: Opaque
data:
  openai-api-key: <base64-encoded-openai-key>
  jwt-secret: <base64-encoded-jwt-secret> 